### ISSUE TITLE
仿微信聊天界面的时间显示问题

### ISSUE THREAD

**Issue by wyh497823256** [drakeet/Effective-MultiType#11]
你好，我现在有一个需求，仿微信聊天界面。我现在仿照 weibo 的demo 来实现。但是在时间显示上卡住了，需求 : 如果两条消息接收时间小于5分钟，那第二条的时间不显示。 我是通过上一个发送时间 和本次消息时间 判断是否显示，但是现在在binder 里面拿不到 上一个消息的数据。

**Comment by drakeet** [comment]
你可以自行把整个列表数据引用都传递给 binder，或者调用 `getAdapter().getItems()` 获得你的 items List。

**Comment by wyh497823256** [comment]
谢谢
