### ISSUE TITLE
onClickListener 点击事件问题

### ISSUE THREAD

**Issue by wyh497823256** [drakeet/Effective-MultiType#12]
如下：
想实现的是，点击item播放一段语音，并且有个动画播放（类似微信）,但现在是点击的item不播放动画，另外一个item 却播放了动画。问题
`public class MessageVoiceBinder extends MessageFrameBinder<VoiceMessage, MessageVoiceBinder.ViewHolder> {

    int screenWidth = 480;
    IMSessionContract.IMSessionPresenter mPresenter;

    public MessageVoiceBinder(Context context, IMSessionContract.IMSessionPresenter imSessionPresenter) {
        super(context);
        screenWidth = ScreenUtils.getScreenWidth();
        this.mPresenter = imSessionPresenter;

    }

    @Override
    protected MessageContentHolder onCreateContentViewHolder(@NonNull LayoutInflater inflater, @NonNull ViewGroup parent) {
        View contentView = inflater.inflate(R.layout.item_message_voice, parent, false);
        return new ViewHolder(contentView, mContext, mPresenter);
    }

    @Override
    protected void onBindContentViewHolder(@NonNull ViewHolder holder,
                                           @NonNull VoiceMessage content,
                                           boolean isSend,
                                           Message.ReceivedStatus messageReceivedStatus,
                                           int messageId) {

        holder.mVoiceMessage = content;
        holder.mMessageId = messageId;
        holder.mReceivedStatus = messageReceivedStatus;

        int increment = (screenWidth / 8 / AppConfig.DEFAULT_MAX_AUDIO_RECORD_TIME_SECOND * content.getDuration());
        if (isSend) {
            holder.item_message_audio_rl_right_layout.setVisibility(View.VISIBLE);
            holder.item_message_audio_rl_left_layout.setVisibility(View.GONE);
            ViewGroup.LayoutParams params = holder.item_message_audio_rl_right_layout_length.getLayoutParams();
            params.width = SizeUtils.dp2px(65) + SizeUtils.dp2px(increment);
            holder.item_message_audio_rl_right_layout_length.setLayoutParams(params);
            holder.item_message_audio_tv_right_duration.setText(content.getDuration() + "''");
        } else {
            holder.item_message_audio_rl_right_layout.setVisibility(View.GONE);
            holder.item_message_audio_rl_left_layout.setVisibility(View.VISIBLE);
            ViewGroup.LayoutParams params = holder.item_message_audio_rl_left_layout_length.getLayoutParams();
            params.width = SizeUtils.dp2px(65) + SizeUtils.dp2px(increment);
            holder.item_message_audio_rl_left_layout_length.setLayoutParams(params);
            holder.item_message_audio_tv_left_duration.setText(content.getDuration() + "''");

        }

        if (messageReceivedStatus.isListened()) {
            holder.item_message_audio_iv_left_read_status.setVisibility(View.GONE);
        } else {
            holder.item_message_audio_iv_left_read_status.setVisibility(View.VISIBLE);

        }

    }

    static class ViewHolder extends MessageContentHolder {

        private FrameLayout item_message_audio_rl_right_layout_length;
        private FrameLayout item_message_audio_rl_left_layout_length;
        private LinearLayout item_message_audio_rl_right_layout;
        private LinearLayout item_message_audio_rl_left_layout;
        private TextView item_message_audio_tv_right_duration;
        private TextView item_message_audio_tv_left_duration;
        private ImageView item_message_audio_iv_right_audio;
        private ImageView item_message_audio_iv_left_audio;
        private ImageView item_message_audio_iv_left_read_status;

        private Timer mTimer;
        private AudioAnimationHandler audioAnimationHandler;
        private TimerTask mTimerTask;
        private int index;

        private VoiceMessage mVoiceMessage;
        private int mMessageId;
        Message.ReceivedStatus mReceivedStatus;

        public ViewHolder(View itemView, Context context, IMSessionContract.IMSessionPresenter imSessionPresenter) {
            super(itemView);
            item_message_audio_rl_right_layout_length = itemView.findViewById(R.id.item_message_audio_rl_right_layout_length);
            item_message_audio_rl_right_layout = itemView.findViewById(R.id.item_message_audio_rl_right_layout);
            item_message_audio_tv_right_duration = itemView.findViewById(R.id.item_message_audio_tv_right_duration);
            item_message_audio_iv_right_audio = itemView.findViewById(R.id.item_message_audio_iv_right_audio);

            item_message_audio_rl_left_layout_length = itemView.findViewById(R.id.item_message_audio_rl_left_layout_length);
            item_message_audio_rl_left_layout = itemView.findViewById(R.id.item_message_audio_rl_left_layout);
            item_message_audio_tv_left_duration = itemView.findViewById(R.id.item_message_audio_tv_left_duration);
            item_message_audio_iv_left_audio = itemView.findViewById(R.id.item_message_audio_iv_left_audio);
            item_message_audio_iv_left_read_status = itemView.findViewById(R.id.item_message_audio_iv_left_read_status);
            item_message_audio_rl_right_layout_length.setOnClickListener(v -> {
                imSessionPresenter.clearMessageReceivedStatus(mMessageId, mReceivedStatus);
                AudioPlayManager.getInstance().startPlay(context, mVoiceMessage.getUri(), new IAudioPlayListener() {
                    @Override
                    public void onStart(Uri var1) {
                        playAudioAnimation(item_message_audio_iv_right_audio, false);
                    }

                    @Override
                    public void onStop(Uri var1) {
                        //停播（一般是停止语音消息动画）
                        stopTimer();
                    }

                    @Override
                    public void onComplete(Uri var1) {
                        //播完（一般是停止语音消息动画）
                        stopTimer();
                    }
                });
            });
            item_message_audio_rl_left_layout_length.setOnClickListener(v -> {
                imSessionPresenter.clearMessageReceivedStatus(mMessageId, mReceivedStatus);
                AudioPlayManager.getInstance().startPlay(context, mVoiceMessage.getUri(), new IAudioPlayListener() {
                    @Override
                    public void onStart(Uri var1) {
                        playAudioAnimation(item_message_audio_iv_left_audio, true);
                    }

                    @Override
                    public void onStop(Uri var1) {
                        //停播（一般是停止语音消息动画）

                        stopTimer();
                    }

                    @Override
                    public void onComplete(Uri var1) {
                        //播完（一般是停止语音消息动画）
                        stopTimer();
                    }
                });
            });

        }

        class AudioAnimationHandler extends Handler {
            ImageView imageView;
            //判断是左对话框还是右对话框
            boolean isleft;

            public AudioAnimationHandler(ImageView imageView, boolean isleft) {
                this.imageView = imageView;
                //判断是左对话框还是右对话框 我这里是在前面设置ScaleType来表示的
                this.isleft = isleft;
            }

            @Override
            public void handleMessage(android.os.Message msg) {
                super.handleMessage(msg);
                switch (msg.what) {
                    case 0:
                        imageView.setImageResource(isleft ? R.drawable.audio_animation_list_left_1 : R.drawable.audio_animation_list_right_1);
                        break;
                    case 1:
                        imageView.setImageResource(isleft ? R.drawable.audio_animation_list_left_2 : R.drawable.audio_animation_list_right_2);
                        break;
                    case 2:
                        imageView.setImageResource(isleft ? R.drawable.audio_animation_list_left_3 : R.drawable.audio_animation_list_right_3);
                        break;
                    default:
                        imageView.setImageResource(isleft ? R.drawable.audio_animation_list_left_3 : R.drawable.audio_animation_list_right_3);
                        break;
                }
            }
        }

        /**
         * 播放语音图标动画
         */
        private void playAudioAnimation(final ImageView imageView, boolean isLeft) {
            //定时器检查播放状态
            stopTimer();
            mTimer = new Timer();
            //将要关闭的语音图片归位
            if (audioAnimationHandler != null) {
                android.os.Message msg = new android.os.Message();
                msg.what = 3;
                audioAnimationHandler.sendMessage(msg);
            }

            audioAnimationHandler = new AudioAnimationHandler(imageView, isLeft);
            mTimerTask = new TimerTask() {

                @Override
                public void run() {
                    index = (index + 1) % 3;
                    android.os.Message msg = new android.os.Message();
                    msg.what = index;
                    audioAnimationHandler.sendMessage(msg);

                }
            };
            mTimer.schedule(mTimerTask, 0, 500);
            //调用频率为500毫秒一次
        }

        /**
         * 停止
         */
        private void stopTimer() {
            if (audioAnimationHandler != null)
                audioAnimationHandler.sendEmptyMessage(3);
            if (mTimer != null) {
                mTimer.cancel();
                mTimer = null;
            }

            if (mTimerTask != null) {
                mTimerTask.cancel();
                mTimerTask = null;
            }

        }
    }

    @Override
    protected void onViewDetachedFromWindow(@NonNull FrameHolder holder) {
        super.onViewDetachedFromWindow(holder);
    }
}
`

**Comment by drakeet** [comment]
MultiType 只是很薄的一层类型分发层，它绝不会改变或影响你的 View 内容及交互逻辑。我看你贴的代码十分复杂而且格式混乱，描述严重不足，这样我是没办法花时间把你理清楚的。你说的问题极有可能是你自己代码的问题，你需要自己寻找原因，或者提供最小相关性可复现你所说的情况的可运行代码项目并付费获得我的帮忙（实际上你的问题和 MultiType 无关）。

**Comment by wyh497823256** [comment]
已经定位的问题
