### ISSUE TITLE
分割线的处理

### ISSUE THREAD

**Issue by Pinned** [drakeet/Effective-MultiType#2]
像微信设置页面，会分成不同的组，组和组之间，有一个比较大的空隙，而组内之间的Item有一个分割线，请问这种有什么比较好的处理方法

**Comment by drakeet** [comment]
有两种做法：
1. 使用 `RecyclerView` 的 `ItemDecoration`.
2. 你可以参考 `GridLayoutManager.setSpanSizeLookup(SpanSizeLookup spanSizeLookup)` 的做法，给 `provider` 传递一个 `Lookup`，告诉其何时使用大空隙，何时隐藏大空隙。

**Comment by Pinned** [comment]
默认的GrideLayoutManager 在计算item的时候，是先计算item的宽度。在减去itemoffset，如果分割线的宽度很大。就能很明显的看出itemsize 在有分割线 与 无分割线上不一样。用itemoffset 并不是最优解，重写layoutmanager 又会略显麻烦。
我提问中说的Layout仅仅是指简单列表。并不是grideLayou  怎么使用spaneSizeLookup ?

**Comment by drakeet** [comment]
我的意思不是叫你去使用 GridLayoutManager，而是教你**仿造/参考** GridLayoutManager.setSpanSizeLookup(SpanSizeLookup spanSizeLookup) 的做法，自行去实现这么一个类似的机制，很容易的。

**Comment by drakeet** [comment]
```
provider.setItemLargeMarginVisibilityLookup(ItemLargeMarginVisibilityLookup lookup)
```
