### ISSUE TITLE
2.4.0新版本 我照着demo写 为什么 适配器的bind方法都不走呢

### ISSUE THREAD

**Issue by KrisLain** [drakeet/Effective-MultiType#3]
每次都只走getcount  但是 bindView的方法 都没有进去，数据一直出不来

**Comment by drakeet** [comment]
你的信息不足以令人了解你的状况和问题原因。请提供完整的可复现示例代码、当前使用的 MultiType 版本号，并且描述清楚你的问题以及你为此做了那些尝试、思考，现在进行到哪一步等等。

**Comment by drakeet** [comment]
另外，目前最新稳定版本是 v2.4.3，如果你怀疑 2.4.0 有问题的话，可以更新到 2.4.3 试试。
